# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc26f6b467aa8dbc002c70df696f1f8a7aa6a5d6fcdc7b0eb14bcf20ae578730cf47e812577e272d5ff558ba704a2bdd81577a5b57fdb723307a2f30723b7380

test:
  secret_key_base: db52fdc8deca92521be7f1bee27ccb2aa35adeb7483c4d798fbea26c111fef505ac81060a4a1c5022f4d87153c58525a243967721cdb72fa78579e08741e2c63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
